### ISSUE TITLE
This file does not appear to be an Mp4 Audio file

### ISSUE THREAD

**Issue by NLLAPPS** [ealva-com/ealvatag#2]
I have seen issue#1 but mine is an audio file created with Android MediaCodec encoder. Do you think MediaCodec creates non conforming M4A too?

Error:
This file does not appear to be an Mp4 Audio file, could be corrupted or video 
2019-01-17 15:13:23.310 1136-1542/com.nll.asr W/System.err:     at yya.<init>(Mp4UdtaBox.java:56)

File: [https://bitbucket.org/ijabz/jaudiotagger/issues/attachments/277/ijabz/jaudiotagger/1547676684.77/277/test%202019_01_16_22_02_03.m4a](https://bitbucket.org/ijabz/jaudiotagger/issues/attachments/277/ijabz/jaudiotagger/1547676684.77/277/test%202019_01_16_22_02_03.m4a)

File info:

General
Complete name                    : C:\Users\Admin\Desktop\test 2019_01_16_22_02_03.m4a
Format                           : MPEG-4
Format profile                   : Base Media / Version 2
Codec ID                         : mp42
File size                        : 166 KiB
Duration                         : 10s 276ms
Overall bit rate                 : 133 Kbps
Encoded date                     : UTC 2019-01-16 22:02:14
Tagged date                      : UTC 2019-01-16 22:02:14
com.android.version              : 8.0.0

Audio
ID                               : 1
Format                           : AAC
Format/Info                      : Advanced Audio Codec
Format profile                   : LC
Codec ID                         : 40
Duration                         : 10s 276ms
Bit rate mode                    : Constant
Bit rate                         : 128 Kbps
Channel(s)                       : 2 channels
Channel positions                : Front: L R
Sampling rate                    : 44.1 KHz
Compression mode                 : Lossy
Stream size                      : 160 KiB (96%)
Title                            : SoundHandle
Language                         : English
Encoded date                     : UTC 2019-01-16 22:02:14
Tagged date                      : UTC 2019-01-16 22:02:14

**Comment by pandasys** [comment]
This is not the same as Issue #1. The file you link doesn't appear to have an Mp4 "meta" box which is the parent of all metadata (tag information) in an Mp4 file. Various other players will play the file but not show metadata. MusicBrainz Picard application can't parse the file either. While the file seems playable (has audio data), it doesn't appear to have associated tag data. I'll investigate a little more when I have time, but it appears this file just doesn't have tag information.

**Comment by NLLAPPS** [comment]
Thanks, just reiterate, file is generated with Android MediaCodec and MediaMuxer.

Can I write tak info with any library?



On January 17, 2019 6:37:01 PM UTC, "Eric A. Snell" <notifications@github.com> wrote:

This is not the same as Issue #1<https://github.com/ealva-com/ealvatag/issues/1>. The file you link doesn't appear to have an Mp4 "meta" box which is the parent of all metadata (tag information) in an Mp4 file. Various other players will play the file but not show metadata. MusicBrainz Picard application can't parse the file either. While the file seems playable (has audio data), it doesn't appear to have associated tag data. I'll investigate a little more when I have time, but it appears this file just doesn't have tag information.
