### ISSUE TITLE
Setting FLAC artwork on Android causes java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Nick80835** [ealva-com/ealvatag#5]
MP3 artwork works fine, only FLAC does this presumably because Android doesn't have ImageIO.

`Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.imageio.ImageIO" on path: DexPathList[[zip file "/data/app/com.nick80835.add-jvbwdoBL7ihYF5PkWATMZw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nick80835.add-jvbwdoBL7ihYF5PkWATMZw==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]`

This happens when attempting to perform addArtwork on the FLAC files tags.

`val thisTempFile = File.createTempFile(thisData.trackId.toString(), ".tmp", cacheDir)
thisTempFile.writeBytes(thisAlbumArtBig)
val thisArtwork = ArtworkFactory.createArtworkFromFile(thisTempFile)
thisAudioTag.addArtwork(thisArtwork)`

**Comment by pandasys** [comment]
I have some FLAC files on an Android device and edited the artwork without error.

Ensure you put this in your code before making any calls to edit a tag
``
    TagOptionSingleton.getInstance().isAndroid = true
``
I put it in onCreate() of my Application subclass. 

If you still have an issue I'll arrange for you to send me the FLAC file and artwork to test.

**Comment by Nick80835** [comment]
That fixed it, I apologize for my ignorance on that.

**Comment by pandasys** [comment]
No apologies needed. I think it's a good defect - just more of a documentation defect. I'll at least update the readme. Thanks.
