### ISSUE TITLE
How to read from stream?

### ISSUE THREAD

**Issue by yzheka** [ealva-com/ealvatag#6]
Is there any way to read from input stream and write to output stream instead of file?

**Comment by pandasys** [comment]
Not currently. That would require all audio file readers and writers to be modified. It's probably a good idea to add this support given Android changes regarding file access. However, it's a non-trivial change and I don't have time at the moment. 

As a suggested workaround, you can copy the stream to a file in a temp dir, modify it, and then copy it back using the output stream. It's not so bad, especially given you may not want to edit the file "in place". This is what I'm currently doing in apps I have that use this library and it's not too onerous.

**Comment by yzheka** [comment]
Good idea. Thanks.
