### ISSUE TITLE
HEY MAATE, JUST DELETE THIS ONE, THANKS

### ISSUE THREAD

**Issue by saladin0x1** [ealva-com/ealvatag#8]

**Comment by pandasys** [comment]
Did you put this:

TagOptionSingleton.getInstance().isAndroid = true;  // Android - put in Application.onCreate()

in your App onCreate as mentioned in the Quick Start part of README?

**Comment by pandasys** [comment]
On Android, `TagOptionSingleton.getInstance().isAndroid = true` is required before any other library operations.
