### ISSUE TITLE
issue with edit tags in android 11

### ISSUE THREAD

**Issue by UtsavG93** [ealva-com/ealvatag#9]
i have taken access by Mediastore.writeRequest() then try to edit
`ealvatag.audio.exceptions.CannotWriteException: ealvatag.audio.exceptions.UnableToCreateFileException: Cannot modify /storage/emulated/0/Music/Chhapaak - Arijit Singh.mp3 because do not have permissions to create files in the folder`

**Comment by pandasys** [comment]
It is a permission issue and not in the scope of ealvatag. Permissions have changed regarding direct file access. The strategy I use is to get an InputStream, copy the file to my app temp area, edit the tag saving it in the temp area, and then get an OutputStream to copy the file back to it's original location. This link https://developer.android.com/about/versions/11/privacy/storage discusses the issue and points to other relavent information. Stackoverflow contains many questions/answers on the issue too, eg. https://stackoverflow.com/questions/60360368/android-11-r-file-path-access

The Android team has made several choices over various releases that greatly complicate the issue. The strategy I use has worked well across releases, but maybe there is another strategy you prefer.

**Comment by pandasys** [comment]
Direct file access is required for some file types and Android has introduced restrictions in recent versions, so a workaround is necessary. Copying the file using input/output streams and editing in app temp area is a possible workaround, with which I've not encountered any issues to-date. Editing a file which is playing is the only time any issue has arisen and I just pause playback during edit. On various recently (last 2-3 years) released devices, if the user edits a file which is playing (such as updating rating), the pause/copy/edit/copy/play cycle is very fast - typically barely audible.
